# Generated by Django 5.2.4 on 2025-07-16 01:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Komponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matgroup_id', models.IntegerField()),
                ('material_id', models.CharField(max_length=100, unique=True)),
                ('material_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('price_reference', models.CharField(max_length=255)),
                ('safety_stock', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('is_disposable', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('broken_stock', models.IntegerField()),
                ('types', models.CharField(blank=True, max_length=100, null=True)),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Komponen',
                'verbose_name_plural': 'Komponen',
            },
        ),
        migrations.CreateModel(
            name='Komputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.CharField(blank=True, max_length=100, null=True)),
                ('dal_code', models.CharField(max_length=100, unique=True)),
                ('inventory_code', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('acquisition_year', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_name', models.CharField(max_length=100)),
                ('machine_condition', models.CharField(choices=[('A', 'Baik Sekali'), ('B', 'Baik'), ('C', 'Kurang Baik'), ('D', 'Rusak')], default='B', max_length=1)),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Komputer',
                'verbose_name_plural': 'Komputer',
            },
        ),
        migrations.CreateModel(
            name='MonitoringStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='unknown', max_length=100)),
                ('komputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_status', to='inventory.komputer')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatKerusakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField()),
                ('komputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kerusakan', to='inventory.komputer')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPerawatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField()),
                ('komputer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_perawatan', to='inventory.komputer')),
            ],
        ),
    ]
