# Generated by Django 5.2.4 on 2025-07-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komputer',
            name='machine_condition',
            field=models.CharField(choices=[('A', 'Baik Sekali'), ('B', 'Baik'), ('C', 'Kurang Baik'), ('D', 'Rusak')], default='B', max_length=50),
        ),
    ]
