# Generated by Django 5.2.4 on 2025-07-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_komputer_machine_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='komputer',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='komputer',
            name='last_ping_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
